Vagrant.configure("2") do |config|
  # 共享文件夹（所有虚拟机都可以访问）
  config.vm.synced_folder "./shared", "/vagrant_shared"  # 将宿主机的 ./shared 映射到虚拟机的 /vagrant_shared
  config.vm.provision "shell", name: "install-dependencies", path: "install-dependencies.sh"
  # Web 服务器
  config.vm.define "mngt" do |web|
    web.vm.box = "hashicorp-education/ubuntu-24-04"
    web.vm.box_version = "0.1.0"
    web.vm.hostname = "mngt"
    web.ssh.username = "vagrant"  # 默认用户名通常是 vagrant
    web.ssh.password = "vagrant"  # 默认密码通常是 vagrant（但导出的 box 可能未保留）
    web.vm.network "private_network",  ip: "192.168.56.3"

    web.vm.provision "shell", name: "install-openvpn", path: "install-openvpn.sh"

    # 启动后获取 IP 并写入共享文件夹
    web.vm.provision "shell", inline: <<-SHELL
      IP=$(ip -4 addr show enp0s8 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
      echo "mngt IP: $IP" > /vagrant_shared/mngt_ip.txt
    SHELL
  end

  # 数据库服务器
  config.vm.define "engine" do |db|
    db.vm.box = "hashicorp-education/ubuntu-24-04"
    db.vm.box_version = "0.1.0"
    db.vm.hostname = "engine"    
    db.ssh.username = "vagrant"  # 默认用户名通常是 vagrant
    db.ssh.password = "vagrant"  # 默认密码通常是 vagrant（但导出的 box 可能未保留）
    db.vm.network "private_network",  ip: "192.168.56.4"

    db.vm.provision "shell", name: "install-openvpn-client", path: "install-openvpn-client.sh"

    # 启动后读取 web 的 IP
    db.vm.provision "shell", inline: <<-SHELL
      IP=$(ip -4 addr show enp0s8 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
      echo "engine IP: $IP" > /vagrant_shared/mngt_ip.txt
      WEB_IP=$(cat /vagrant_shared/mngt_ip.txt | grep -oP '(?<=mngt IP: )\S+')
      echo "engine is connecting to mngt at: $WEB_IP" > /vagrant_shared/engine_connection.txt
    SHELL
  end
end